services:
  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: kv2
      MYSQL_PASSWORD: "12345"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --innodb_data_file_path=ibdata1:10M:autoextend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 30s
