micronaut:
  http:
    client:
      log-level: DEBUG
datasources:
  default:
    # auto-run testcontainer mysql
    url: jdbc:tc:mysql:8:///kv2
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: kv2
    password: '12345'
    dialect: MYSQL
