micronaut:
  application:
    name: kv2
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: ${OAUTH_CLIENT_ID:test_client_id}
          client-secret: ${OAUTH_CLIENT_SECRET:test_client_secret}
          openid:
            issuer: ${OAUTH_ISSUER:test_google_issuer}
    endpoints:
      logout:
        get-allowed: true
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
