datasource:
  url: ${DB_URL:jdbc:mysql://localhost:3306/db}
  username: ${DB_USERNAME:kv2}
  password: ${DB_PASSWORD:12345}
  driverClassName: com.mysql.cj.jdbc.Driver

assets:
  styles:
    - style
    - font-awesome/6.4.0/css/fontawesome
    - font-awesome/6.4.0/css/solid
    - codemirror/6.65.7/lib/codemirror
  scripts:
    - editor
    - codemirror/6.65.7/lib/codemirror

kv2:
  jte:
    dynamic: false
    dynamic-source-path: views/src/main/jte
  oauth:
    discord:
      client-id: ${DISCORD_CLIENT_ID:test_discord_id}
      client-secret: ${DISCORD_CLIENT_SECRET:test_discord_secret}
      redirect-uri: ${DISCORD_REDIRECT_URI:http://localhost:8080/oauth/discord/callback}
  security:
    jwt-secret: ${JWT_SECRET:MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTE=}
