name: frontend build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.0
          cache: 'pnpm'
          cache-dependency-path: 'client/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: run test
        run: pnpm jest
      - name: run build
        run: pnpm quasar build

